Add color output to 'goad test' for final status.
Goconvey output is gorgeous and all, but it doesn't really do the greatest job of overall summary... we only have the exit code of `go test` as a whole for that.  So, might as well light it up.  Suffixing my up-enter shell content with `echo $?` was getting old.

Signed-off-by: Eric Myhre <hash@exultant.us>

diff --git a/goad b/goad
--- a/goad
+++ b/goad
@@ -49,7 +49,12 @@ else
 		;;
 	test)
 		go test -i "$SUBSECTION" 2> >(grep --color -E "$highlighRegex") &&
-		go test -v "$SUBSECTION" 2> >(grep --color -E "$highlighRegex")
+		go test -v "$SUBSECTION" 2> >(grep --color -E "$highlighRegex") && {
+			echo -e "\n\E[1;32mall tests green.\E[0;m"
+		} || {
+			echo -e "\n\E[1;41msome tests failed!\E[0;m"
+			exit 4
+		}
 		;;
 	install)
 		go install "$pkg" 2> >(grep --color -E "$highlighRegex")
